{% set name = "crystaltoolkit-extension" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crystaltoolkit-extension-{{ version }}.tar.gz
  sha256: c07119182aa8252c09fb4c6bcd7a0901a5463970094c1367f624c8319bb8478e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - jupyter_packaging >=0.7.9
    - jupyterlab >=3,<4
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.6
    - jupyterlab >=3,<4

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/crystaltoolkit
  summary: A JupyterLab extension for rendering Crystal Toolkit Scene JSON files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
